#!/usr/bin/env sh
# RSS generator module
__module_name__='posts-rss'

# defaults variables
	posts__dbdir='posts'
	. "${SSG__modules}/posts/defaults.rc.d/posts.rc"
	. "${0%/*}/defaults.rc.d/posts-rss.rc"

# variables
	. "${SSG__lib}/import-includes.rc"
	. "${SSG__lib}/import-defaults.rc"

# check variables
	"${posts_rss__force_enable}" || if [ "${posts_rss__url}" = '' ]; then
		echo 'RSS URL is not set - module disabled'
		exit 1
	fi

# directory in database
	if [ ! -e "${SSG__database}/${posts__dbdir}" ]; then
		echo '"'"${posts__dbdir}"'" directory not found in database'
		exit 1
	fi

# header
	[ ! -e "${SSG__generated}/${posts_rss__generated_directory}" ] && mkdir -p "${SSG__generated}/${posts_rss__generated_directory}"
	echo "${posts_rss__header_content}"'<?xml version="1.0" encoding="UTF-8" ?>' > "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"
	echo '<rss version="2.0"><channel>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"
		echo '<title>'"${posts_rss__title}"'</title>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"
		echo '<link>'"${posts_rss__link}"'</link>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"
		[ ! "${posts_rss__lang}" = '' ] && echo '<language>'"${posts_rss__lang}"'</language>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"

# database processing (reverse order)
	posts__post_pivot=''
	for post in ${SSG__database}/${posts__dbdir}/public_*; do
		posts__post_pivot="${post} ${posts__post_pivot}"
	done
	post="${posts__post_pivot}"
	unset 'posts__post_pivot'

	for post in ${post}; do
		[ "${post}" = "${SSG__database}/${posts__dbdir}/public_*" ] && break
		echo " Adding post ${post##*/}"

		. "${post}/meta.rc"
		echo '<item>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"
			[ "${posts_rss__post_title}" = '' ] && \
				echo '<title></title>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}" || \
				echo '<title>'"${posts_rss__post_title}"'</title>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"
			echo '<link>'"${posts_rss__url}${defaults__url_prefix}/${posts__generated_post_directory}${post##*_}"'</link>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"
			[ ! "${posts_rss__post_pubdate}" = '' ] && echo '<pubDate>'"${posts_rss__post_pubdate}"'</pubDate>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"
			[ "${posts_rss__post_description}" = '' ] && \
				echo '<description></description>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}" || \
				echo '<description>'"${posts_rss__post_description}"'</description>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"
				[ ! "${posts_rss__post_xml}" = '' ] && echo "${posts_rss__post_xml}" >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"
		echo '</item>' >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"

		unset 'posts_rss__post_title'
		unset 'posts_rss__post_description'
		unset 'posts_rss__post_pubdate'
		unset 'posts_rss__post_xml'
	done

# footer
	echo '</channel></rss>'"${posts_rss__footer_content}" >> "${SSG__generated}/${posts_rss__generated_directory}${posts_rss__file}"

# you can't do that
	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1

exit 0
