#!/usr/bin/env sh
# Post archive generator module
[ ! "${@}" = '' ] && exit 1
__module_name__='posts-arch'

# defaults variables
	posts__dbdir='posts'
	. "${SSG__modules}/posts/defaults.rc.d/posts.rc"
	. "${0%/*}/defaults.rc.d/posts-arch.rc"

# variables
	. "${SSG__lib}/import-includes.rc"
	. "${SSG__lib}/import-defaults.rc"
	[ "${posts_arch__generated_directory}" = '' ] && posts_arch__generated_directory='arch'

# functions
	. "${0%/*}/../posts/generate_post_box.rc"

# directory in database
	if [ ! -e "${SSG__database}/${posts__dbdir}" ]; then
		echo '"'"${posts__dbdir}"'" directory not found in database'
		exit 1
	fi

# database processing
	post_arch__date_list=''

	for post in ${SSG__database}/${posts__dbdir}/public_*; do
		[ "${post}" = "${SSG__database}/${posts__dbdir}/public_*" ] && break

		for post_arch in ${post}/arch_*; do
			[ "${post_arch}" = "${post}/arch_*" ] && break

			post_arch=${post_arch##*/}
			post_arch__date_list="${post_arch#*_} ${post_arch__date_list}"
		done
	done

	# deduplicate date list
	[ ! "${post_arch__date_list}" = '' ] && \
		post_arch__date_list="$(echo -n "${post_arch__date_list}" | tr ' ' '\n' | uniq)"

# date list processing
	posts_arch__generate_date_list()
	{
		local template__html_headers=''
		local template__html_title=''

		posts_arch__list_html_headers
		posts_arch__html_title

		posts_arch__list_header_content
		templates__current_get_part 'top'

		if ! templates__current_get_part 'resource' 'arch-list'; then
			echo "error: template ${templates__template} does not provide arch-list.rc" >&2
		fi

		templates__current_get_part 'bottom'
		posts_arch__list_footer_content
	}

	[ ! -e "${SSG__generated}/${posts_arch__generated_directory}" ] && mkdir -p "${SSG__generated}/${posts_arch__generated_directory}"

	if "${posts_arch__enable_date_lists}"; then
		if "${posts_arch__parallel_rendering}"; then
			posts_arch__generate_date_list > "${SSG__generated}/${posts_arch__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}" &
		else
			posts_arch__generate_date_list > "${SSG__generated}/${posts_arch__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}"
		fi
	else
		echo 'Date list generation is disabled'
	fi

# date listings processing
	if [ ! "${post_arch__date_list}" = '' ]; then
		posts_arch__generate_list()
		{
			local post
			local rendered_post
			local current_post_number='1'
			local current_page_number='1'
			local rendered_page_dir_number=''

			for post in ${1}; do
				post="${post%/*}"

				if [ ! "${current_page_number}" = '1' ] && [ "${current_post_number}" = '1' ]; then
					rendered_page_dir_number="/${current_page_number}"
					mkdir "${rendered_page_dir}${rendered_page_dir_number}"
				fi

				if [ "${current_post_number}" = '1' ]; then
					echo " Processing page ${current_page_number}"

					template__html_headers=''
					template__html_title=''

					posts_arch__listing_html_headers
					posts_arch__list_html_title

					posts_arch__listing_header_content > "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
					templates__current_get_part 'top' >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
				fi

				rendered_post="${post##*_}"
				echo "  Adding post ${rendered_post}"
				generate_post_box >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"

				if [ "${current_post_number}" = "${posts__posts_per_page}" ]; then
					if ! templates__current_get_part 'resource' 'arch-pages' >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"; then
						echo "error: template ${templates__template} does not provide arch-pages.rc"
					fi

					templates__current_get_part 'bottom' >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
					posts_arch__listing_footer_content >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"

					current_post_number='1'
					current_page_number="$((current_page_number+1))"

					continue
				fi

				current_post_number="$((current_post_number+1))"
			done

			if [ ! "${current_post_number}" = "${posts__posts_per_page}" ] && [ ! "${current_post_number}" = '1' ]; then
				if ! templates__current_get_part 'resource' 'arch-pages' >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"; then
					echo "error: template ${templates__template} does not provide arch-pages.rc"
				fi

				templates__current_get_part 'bottom' >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
				posts_arch__listing_footer_content >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
			fi
		}

		for date in ${post_arch__date_list}; do
			echo "Processing date ${date}"

			rendered_page_dir="${SSG__generated}/${posts_arch__generated_directory}/${date}"
			mkdir "${rendered_page_dir}"

			posts_arch__counted_posts='0'
			posts_arch__counted_posts_find="$(find ${SSG__database}/${posts__dbdir}/public_* -type f -path "*/arch_${date}" | tac)" # cache

			for post in ${posts_arch__counted_posts_find}; do
				posts_arch__counted_posts="$((posts_arch__counted_posts+1))"
			done

			posts_arch__counted_pages="$(awk '
				BEGIN {
					printf \
						"%.0d", \
						('"${posts_arch__counted_posts}"'/'"${posts__posts_per_page}"')+0.9 \
				}
			')"

			if "${posts_arch__parallel_rendering}"; then
				posts_arch__generate_list "${posts_arch__counted_posts_find}" &
				continue
			fi

			posts_arch__generate_list "${posts_arch__counted_posts_find}"
		done

		"${posts_arch__parallel_rendering}" && wait
	fi

# home page processing
	[ "${defaults__home_module}" = "${__module_name__}" ] && if "${posts_arch__enable_date_lists}"; then
		echo 'This is default module - generating home page'
		mv "${SSG__generated}/${posts_arch__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
	else
		echo 'Error: posts_arch__enable_date_lists is false - this module cannot be the default module'
		exit 1
	fi

exit 0
