#!/usr/bin/env sh
# Compressor module
__module_name__='z-z_gzip'

# defaults variables
	. "${0%/*}/defaults.rc.d/gzip.rc"

# variables
	. "${SSG__lib}/import-defaults.rc"

if [ "${gzip__compression}" = '' ]; then
	echo 'Gzip compression is disabled in settings'
else
	find ${SSG__generated} -name '*.html' -or -name '*.css' -or -name '*.js' -or -name '*.xml' | while read file; do
		case "${file##*.}" in
			'html')
				"${gzip__process_html}" || continue
			;;
			'css')
				"${gzip__process_css}" || continue
			;;
			'js')
				"${gzip__process_js}" || continue
			;;
			'xml')
				"${gzip__process_xml}" || continue
			;;
		esac

		echo "Zipping $(echo -n "${file}" | sed 's|'"${SSG__generated}"'||g')"
		gzip "-${gzip__compression}" "${file}"

		"${gzip__remove_gz_extension}" && \
			mv "${file}.gz" "${file}"
	done
fi

# you can't do that
	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1

exit 0
