#!/usr/bin/env sh
# Compressor module
[ ! "${@}" = '' ] && exit 1
__module_name__='z-z_gzip'

# defaults variables
	. "${0%/*}/defaults.rc.d/gzip.rc"

# variables
	. "${SSG__lib}/import-defaults.rc"

	"${gzip__process_html}" && gzip__process_files="${gzip__process_files} *.html *.htm *.xhtml"
	"${gzip__process_css}" && gzip__process_files="${gzip__process_files} *.css"
	"${gzip__process_js}" && gzip__process_files="${gzip__process_files} *.js"
	"${gzip__process_xml}" && gzip__process_files="${gzip__process_files} *.xml *.xsl"

# functions
	. "${0%/*}/functions.rc"

if [ "${gzip__compression}" = '' ]; then
	echo 'Gzip compression is disabled in settings'
else
	ssg_gzip "${gzip__compression}" "${gzip__remove_gz_extension}" "${gzip__process_files}"
fi

# you can't do that
	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1

exit 0
