#!/usr/bin/env sh
# Copy static files to public directory
__module_name__='static'

static__dbdir='static'

if [ -e "${SSG__database}/${static__dbdir}" ]; then
		echo 'Copying static files'
		[ ! -e "${SSG__generated}" ] && mkdir -p "${SSG__generated}"
		cp -rfp ${SSG__database}/${static__dbdir}/* "${SSG__generated}"
		for hiddenfile in ${SSG__database}/${static__dbdir}/.*; do
			if [ ! "${hiddenfile}" = "${SSG__database}/${static__dbdir}/." ] && [ ! "${hiddenfile}" = "${SSG__database}/${static__dbdir}/.." ]; then
				cp -rfp "${hiddenfile}" "${SSG__generated}"
			fi
		done
else
	echo '"'"${static__dbdir}"'" directory not found in database'
fi

# you can't do that
	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1

exit 0
