#!/usr/bin/env sh
# Copy static files to public directory
[ ! "${@}" = '' ] && exit 1
__module_name__='static'

# defaults variables
	static__dbdir='static'

# variables
	. "${SSG__lib}/import-defaults.rc"

if [ -e "${SSG__database}/${static__dbdir}" ]; then
		echo 'Copying static files'

		[ ! -e "${SSG__generated}" ] && mkdir -p "${SSG__generated}"
		cp -rfp ${SSG__database}/${static__dbdir}/* "${SSG__generated}"

		for hiddenfile in ${SSG__database}/${static__dbdir}/.*; do
			if [ "${hiddenfile}" = "${SSG__database}/${static__dbdir}/." ] || [ "${hiddenfile}" = "${SSG__database}/${static__dbdir}/.." ]; then
				continue
			fi

			cp -rfp "${hiddenfile}" "${SSG__generated}"
		done
else
	echo 'Error: "'"${static__dbdir}"'" directory not found in database'
	exit 1
fi

# you can't do that
	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1

exit 0
