#!/usr/bin/env sh
# sitemap.xml generator
__module_name__='z-a_sitemap'

# defaults variables
	. "${0%/*}/defaults.rc.d/sitemap.rc"

# variables
	. "${SSG__lib}/import-defaults.rc"

# check if enabled
	if ! "${sitemap__enabled}"; then
		echo 'Sitemap generation is disabled in settings'
		find -type f -name 'exclude-from-sitemap' | while read file; do
			rm "${file}"
		done
		exit 0
	fi

# check variables
	if [ ! -e "${SSG__generated}" ]; then
		echo "${SSG__generated} not exists"
		exit 1
	fi
	if [ "${sitemap__page_domain}" = '' ] || [ "${sitemap__sitemap_file_name}" = '' ]; then
		echo 'Error: no domain or sitemap defined'
		exit 1
	fi
	echo 'Generating sitemap...'

# save sitemap.xml header
	echo "${sitemap__header_content}"'<?xml version="1.0" encoding="UTF-8" ?>' > "${SSG__generated}/${sitemap__sitemap_file_name}"
	echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> "${SSG__generated}/${sitemap__sitemap_file_name}"

# find ${defaults__default_file_name}${defaults__default_file_extension} files
	cd "${SSG__generated}"
	find -name "${defaults__default_file_name}${defaults__default_file_extension}" -type f | while read file; do
		file="${file#?}"
		if [ -e "${SSG__generated}${file%/*}/exclude-from-sitemap" ]; then
			echo " 'exclude-from-sitemap' exists in ${file%/*} - excluded"
			rm "${SSG__generated}${file%/*}/exclude-from-sitemap"
		else
			echo '<url>' >> "${SSG__generated}/${sitemap__sitemap_file_name}"
				echo "<loc>${sitemap__page_domain}${file%/*}/</loc>" >> "${SSG__generated}/${sitemap__sitemap_file_name}"
				echo "<lastmod>$(date '+%Y-%m-%d')</lastmod>" >> "${SSG__generated}/${sitemap__sitemap_file_name}"
				echo "<changefreq>${sitemap__param_changefreq}</changefreq>" >> "${SSG__generated}/${sitemap__sitemap_file_name}"
				echo '<priority>0.5</priority>' >> "${SSG__generated}/${sitemap__sitemap_file_name}"
			echo '</url>' >> "${SSG__generated}/${sitemap__sitemap_file_name}"
		fi
	done

# find other .html files
	cd "${SSG__generated}"
	find -name '*.html' -type f -not -name "${defaults__default_file_name}${defaults__default_file_extension}" | while read file; do
		file="${file#?}"
		if [ -e "${SSG__generated}${file}__exclude-from-sitemap" ]; then
			echo " '${SSG__generated}${file}__exclude-from-sitemap' exists - excluded"
			rm "${SSG__generated}${file}__exclude-from-sitemap"
		else
			echo '<url>' >> "${SSG__generated}/${sitemap__sitemap_file_name}"
				echo "<loc>${sitemap__page_domain}${file}</loc>" >> "${SSG__generated}/${sitemap__sitemap_file_name}"
				echo "<lastmod>$(date '+%Y-%m-%d')</lastmod>" >> "${SSG__generated}/${sitemap__sitemap_file_name}"
				echo "<changefreq>${sitemap__param_changefreq}</changefreq>" >> "${SSG__generated}/${sitemap__sitemap_file_name}"
				echo '<priority>0.5</priority>' >> "${SSG__generated}/${sitemap__sitemap_file_name}"
			echo '</url>' >> "${SSG__generated}/${sitemap__sitemap_file_name}"
		fi
	done

# save sitemap.xml footer
	echo -n '</urlset>'"${sitemap__footer_content}" >> "${SSG__generated}/${sitemap__sitemap_file_name}"

# gzip sitemap.xml
	if [ ! "${sitemap__gzip_sitemap_xml}" = '' ]; then
		gzip "-${sitemap__gzip_sitemap_xml}" "${SSG__generated}/${sitemap__sitemap_file_name}"

		"${sitemap__remove_gz_extension}" && \
			mv "${SSG__generated}/${sitemap__sitemap_file_name}.gz" "${SSG__generated}/${sitemap__sitemap_file_name}"
	fi

# save info to robots.txt
	if "${sitemap__save_info_to_robots_txt}"; then
		[ -e "${SSG__generated}/robots.txt" ] && echo '' >> "${SSG__generated}/robots.txt"
		if [ "${sitemap__gzip_sitemap_xml}" = '' ]; then
			echo "Sitemap: ${sitemap__page_domain}/${sitemap__sitemap_file_name}" >> "${SSG__generated}/robots.txt"
		else
			echo "Sitemap: ${sitemap__page_domain}/${sitemap__sitemap_file_name}.gz" >> "${SSG__generated}/robots.txt"
		fi
	fi

# you can't do that
	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1

exit 0
