#!/usr/bin/env sh
# minifier module
[ ! "${@}" = '' ] && exit 1
__module_name__='z-y_minify'

# defaults variables
	. "${0%/*}/defaults.rc.d/minify.rc"

# variables
	. "${SSG__lib}/import-defaults.rc"

	if "${minify__process_all}"; then
		minify__process_html='true'
		minify__process_css='true'
		minify__process_js='true'
	fi

# functions
	. "${0%/*}/functions.rc"

# minify html
	if "${minify__process_html}"; then
		if "${minify__parallel_rendering}"; then
			minify_html '*.html' "${minify__process_html_comments}" &
			minify_html '*.htm' "${minify__process_html_comments}" &
		else
			minify_html '*.html' "${minify__process_html_comments}"
			minify_html '*.htm' "${minify__process_html_comments}"
		fi
	else
		echo 'HTML minification is disabled in settings'
	fi

# minify css
	if "${minify__process_css}"; then
		if "${minify__parallel_rendering}"; then
			minify_css &
		else
			minify_css
		fi
	else
		echo 'CSS minification is disabled in settings'
	fi

# minify js
	if "${minify__process_js}"; then
		if "${minify__parallel_rendering}"; then
			minify_js &
		else
			minify_js
		fi
	else
		echo 'JS minification is disabled in settings'
	fi

"${minify__parallel_rendering}" && wait

# you can't do that
	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1

exit 0
